language: node_js
node_js: '10'

cache: yarn

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.0
  - export PATH="$HOME/.yarn/bin:$PATH"
